interface IData {
  iD: number;
  name: string;
  email: string;
  status: string;
  availability: string;
  location: string;
  joined: string;
  "balance($)": number;
  avatar: string;
  flag: string;
  company: string;
  role: string;
}

export const data: IData[] = [
  {
    iD: 1,
    name: "Kathryn Campbell",
    email: "kathryn@apple.com",
    status: "active",
    availability: "online",
    location: "San Francisco, USA",
    joined: "2021-04-15",
    "balance($)": 5143.03,
    avatar: "1.png",
    flag: "🇺🇸",
    company: "Apple",
    role: "CEO",
  },
  {
    iD: 2,
    name: "Robert Smith",
    email: "robert@openai.com",
    status: "inactive",
    availability: "away",
    location: "London, UK",
    joined: "2020-07-20",
    "balance($)": 4321.87,
    avatar: "2.png",
    flag: "🇬🇧",
    company: "OpenAI",
    role: "CTO",
  },
  {
    iD: 3,
    name: "Sophia Johnson",
    email: "sophia@meta.com",
    status: "active",
    availability: "busy",
    location: "Toronto, Canada",
    joined: "2019-03-12",
    "balance($)": 7654.98,
    avatar: "3.png",
    flag: "🇨🇦",
    company: "Meta",
    role: "Designer",
  },
  {
    iD: 4,
    name: "Lucas Walker",
    email: "lucas@tesla.com",
    status: "inactive",
    availability: "offline",
    location: "Sydney, Australia",
    joined: "2022-01-18",
    "balance($)": 3456.45,
    avatar: "4.png",
    flag: "🇦🇺",
    company: "Tesla",
    role: "Developer",
  },
  {
    iD: 5,
    name: "Emily Davis",
    email: "emily@sap.com",
    status: "active",
    availability: "online",
    location: "Berlin, Germany",
    joined: "2023-05-23",
    "balance($)": 9876.54,
    avatar: "5.png",
    flag: "🇩🇪",
    company: "SAP",
    role: "Lawyer",
  },
  {
    iD: 6,
    name: "James Lee",
    email: "james@keenthemes.com",
    status: "active",
    availability: "away",
    location: "Kuala Lumpur, MY",
    joined: "2018-11-30",
    "balance($)": 6214.22,
    avatar: "6.png",
    flag: "🇲🇾",
    company: "Keenthemes",
    role: "Director",
  },
  {
    iD: 7,
    name: "Isabella Martinez",
    email: "isabella@bbva.es",
    status: "inactive",
    availability: "busy",
    location: "Barcelona, Spain",
    joined: "2021-06-14",
    "balance($)": 5321.77,
    avatar: "7.png",
    flag: "🇪🇸",
    company: "BBVA",
    role: "Product Manager",
  },
  {
    iD: 8,
    name: "Benjamin Harris",
    email: "benjamin@sony.jp",
    status: "active",
    availability: "offline",
    location: "Tokyo, Japan",
    joined: "2020-10-22",
    "balance($)": 8452.39,
    avatar: "8.png",
    flag: "🇯🇵",
    company: "Sony",
    role: "Marketing Lead",
  },
  {
    iD: 9,
    name: "Olivia Brown",
    email: "olivia@lvmh.fr",
    status: "active",
    availability: "online",
    location: "Paris, France",
    joined: "2019-09-17",
    "balance($)": 7345.1,
    avatar: "9.png",
    flag: "🇫🇷",
    company: "LVMH",
    role: "Data Scientist",
  },
  {
    iD: 10,
    name: "Michael Clark",
    email: "michael@eni.it",
    status: "inactive",
    availability: "away",
    location: "Milan, Italy",
    joined: "2023-02-11",
    "balance($)": 5214.88,
    avatar: "10.png",
    flag: "🇮🇹",
    company: "ENI",
    role: "Engineer",
  },
  {
    iD: 11,
    name: "Ava Wilson",
    email: "ava@vale.br",
    status: "active",
    availability: "busy",
    location: "Rio de Janeiro, Brazil",
    joined: "2022-12-01",
    "balance($)": 9421.5,
    avatar: "11.png",
    flag: "🇧🇷",
    company: "Vale",
    role: "Software Engineer",
  },
  {
    iD: 12,
    name: "David Young",
    email: "david@tata.in",
    status: "active",
    availability: "offline",
    location: "Mumbai, India",
    joined: "2020-03-27",
    "balance($)": 4521.67,
    avatar: "12.png",
    flag: "🇮🇳",
    company: "Tata",
    role: "Sales Manager",
  },
];
