ALTER TABLE workspaces REPLICA IDENTITY FULL;
ALTER TABLE forms REPLICA IDENTITY FULL;
ALTER TABLE submissions REPLICA IDENTITY FULL;
ALTER TABLE form_favorites REPLICA IDENTITY FULL;
ALTER TABLE form_versions REPLICA IDENTITY FULL;
