CREATE TABLE "form_settings" (
	"id" text PRIMARY KEY,
	"formId" text NOT NULL,
	"language" text DEFAULT 'English' NOT NULL,
	"redirectOnCompletion" boolean DEFAULT false NOT NULL,
	"redirectUrl" text,
	"redirectDelay" integer DEFAULT 0 NOT NULL,
	"progressBar" boolean DEFAULT false NOT NULL,
	"branding" boolean DEFAULT true NOT NULL,
	"autoJump" boolean DEFAULT false NOT NULL,
	"saveAnswersForLater" boolean DEFAULT true NOT NULL,
	"selfEmailNotifications" boolean DEFAULT false NOT NULL,
	"notificationEmail" text,
	"respondentEmailNotifications" boolean DEFAULT false NOT NULL,
	"respondentEmailSubject" text,
	"respondentEmailBody" text,
	"passwordProtect" boolean DEFAULT false NOT NULL,
	"password" text,
	"closeForm" boolean DEFAULT false NOT NULL,
	"closedFormMessage" text DEFAULT 'This form is now closed.',
	"closeOnDate" boolean DEFAULT false NOT NULL,
	"closeDate" text,
	"limitSubmissions" boolean DEFAULT false NOT NULL,
	"maxSubmissions" integer,
	"preventDuplicateSubmissions" boolean DEFAULT false NOT NULL,
	"dataRetention" boolean DEFAULT false NOT NULL,
	"dataRetentionDays" integer,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "form_settings" ADD CONSTRAINT "form_settings_formId_forms_id_fkey" FOREIGN KEY ("formId") REFERENCES "forms"("id") ON DELETE CASCADE;