ALTER TABLE "form_settings" ADD COLUMN "redirectDelay" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "form_settings" ADD COLUMN "branding" boolean DEFAULT true NOT NULL;--> statement-breakpoint
ALTER TABLE "form_settings" DROP COLUMN "tallyBranding";--> statement-breakpoint
ALTER TABLE "account" ALTER COLUMN "accessTokenExpiresAt" SET DATA TYPE timestamp with time zone USING "accessTokenExpiresAt"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "account" ALTER COLUMN "refreshTokenExpiresAt" SET DATA TYPE timestamp with time zone USING "refreshTokenExpiresAt"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "account" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "account" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone USING "updatedAt"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "apikey" ALTER COLUMN "lastRefillAt" SET DATA TYPE timestamp with time zone USING "lastRefillAt"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "apikey" ALTER COLUMN "lastRequest" SET DATA TYPE timestamp with time zone USING "lastRequest"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "apikey" ALTER COLUMN "expiresAt" SET DATA TYPE timestamp with time zone USING "expiresAt"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "apikey" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "apikey" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone USING "updatedAt"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "form_analytics_daily" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "form_analytics_daily" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone USING "updatedAt"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "form_dropoff_daily" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "form_dropoff_daily" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone USING "updatedAt"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "form_favorites" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "form_question_progress" ALTER COLUMN "viewedAt" SET DATA TYPE timestamp with time zone USING "viewedAt"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "form_question_progress" ALTER COLUMN "startedAt" SET DATA TYPE timestamp with time zone USING "startedAt"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "form_question_progress" ALTER COLUMN "completedAt" SET DATA TYPE timestamp with time zone USING "completedAt"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "form_question_progress" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "form_settings" ALTER COLUMN "closeDate" SET DATA TYPE timestamp with time zone USING "closeDate"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "form_settings" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "form_settings" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone USING "updatedAt"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "form_share_settings" ALTER COLUMN "expiresAt" SET DATA TYPE timestamp with time zone USING "expiresAt"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "form_share_settings" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "form_share_settings" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone USING "updatedAt"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "form_versions" ALTER COLUMN "publishedAt" SET DATA TYPE timestamp with time zone USING "publishedAt"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "form_versions" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "form_visits" ALTER COLUMN "visitStartedAt" SET DATA TYPE timestamp with time zone USING "visitStartedAt"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "form_visits" ALTER COLUMN "visitEndedAt" SET DATA TYPE timestamp with time zone USING "visitEndedAt"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "form_visits" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "form_visits" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone USING "updatedAt"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "forms" ALTER COLUMN "deletedAt" SET DATA TYPE timestamp with time zone USING "deletedAt"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "forms" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "forms" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone USING "updatedAt"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "invitation" ALTER COLUMN "expiresAt" SET DATA TYPE timestamp with time zone USING "expiresAt"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "invitation" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "member" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "organization" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "session" ALTER COLUMN "expiresAt" SET DATA TYPE timestamp with time zone USING "expiresAt"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "session" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "session" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone USING "updatedAt"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "submissions" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "submissions" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone USING "updatedAt"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "todos" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "user" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "user" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone USING "updatedAt"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "verification" ALTER COLUMN "expiresAt" SET DATA TYPE timestamp with time zone USING "expiresAt"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "verification" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "verification" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone USING "updatedAt"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "workspaces" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone USING "createdAt"::timestamp with time zone;--> statement-breakpoint
ALTER TABLE "workspaces" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone USING "updatedAt"::timestamp with time zone;