/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RscTestRouteImport } from './routes/rsc-test'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as LoginEmailRouteImport } from './routes/login/email'
import { Route as FormsFormIdRouteImport } from './routes/forms/$formId'
import { Route as FFormIdRouteImport } from './routes/f/$formId'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as FormsI8nFormIdRouteImport } from './routes/forms/$i8n.$formId'
import { Route as ApiIconsNameRouteImport } from './routes/api/icons/$name'
import { Route as ApiCronPurgeArchivedFormsRouteImport } from './routes/api/cron/purge-archived-forms'
import { Route as ApiCronAggregateAnalyticsRouteImport } from './routes/api/cron/aggregate-analytics'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAiFormGenerateRouteImport } from './routes/api/ai/form-generate'
import { Route as AuthenticatedWorkspaceWorkspaceIdRouteRouteImport } from './routes/_authenticated/workspace/$workspaceId/route'
import { Route as ApiFormsFormIdMetaRouteImport } from './routes/api/forms/$formId/meta'
import { Route as AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRouteImport } from './routes/_authenticated/workspace/$workspaceId/form-builder/$formId/route'
import { Route as AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdSubmissionsRouteImport } from './routes/_authenticated/workspace/$workspaceId/form-builder/$formId/submissions'
import { Route as AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdSettingsRouteImport } from './routes/_authenticated/workspace/$workspaceId/form-builder/$formId/settings'
import { Route as AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdInsightsRouteImport } from './routes/_authenticated/workspace/$workspaceId/form-builder/$formId/insights'
import { Route as AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdEditRouteImport } from './routes/_authenticated/workspace/$workspaceId/form-builder/$formId/edit'

const RscTestRoute = RscTestRouteImport.update({
  id: '/rsc-test',
  path: '/rsc-test',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginEmailRoute = LoginEmailRouteImport.update({
  id: '/login/email',
  path: '/login/email',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsFormIdRoute = FormsFormIdRouteImport.update({
  id: '/forms/$formId',
  path: '/forms/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const FFormIdRoute = FFormIdRouteImport.update({
  id: '/f/$formId',
  path: '/f/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const FormsI8nFormIdRoute = FormsI8nFormIdRouteImport.update({
  id: '/forms/$i8n/$formId',
  path: '/forms/$i8n/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIconsNameRoute = ApiIconsNameRouteImport.update({
  id: '/api/icons/$name',
  path: '/api/icons/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronPurgeArchivedFormsRoute =
  ApiCronPurgeArchivedFormsRouteImport.update({
    id: '/api/cron/purge-archived-forms',
    path: '/api/cron/purge-archived-forms',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronAggregateAnalyticsRoute =
  ApiCronAggregateAnalyticsRouteImport.update({
    id: '/api/cron/aggregate-analytics',
    path: '/api/cron/aggregate-analytics',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiFormGenerateRoute = ApiAiFormGenerateRouteImport.update({
  id: '/api/ai/form-generate',
  path: '/api/ai/form-generate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspaceWorkspaceIdRouteRoute =
  AuthenticatedWorkspaceWorkspaceIdRouteRouteImport.update({
    id: '/workspace/$workspaceId',
    path: '/workspace/$workspaceId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiFormsFormIdMetaRoute = ApiFormsFormIdMetaRouteImport.update({
  id: '/api/forms/$formId/meta',
  path: '/api/forms/$formId/meta',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRoute =
  AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRouteImport.update({
    id: '/form-builder/$formId',
    path: '/form-builder/$formId',
    getParentRoute: () => AuthenticatedWorkspaceWorkspaceIdRouteRoute,
  } as any)
const AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdSubmissionsRoute =
  AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdSubmissionsRouteImport.update(
    {
      id: '/submissions',
      path: '/submissions',
      getParentRoute: () =>
        AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRoute,
    } as any,
  )
const AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdSettingsRoute =
  AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () =>
      AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRoute,
  } as any)
const AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdInsightsRoute =
  AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdInsightsRouteImport.update({
    id: '/insights',
    path: '/insights',
    getParentRoute: () =>
      AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRoute,
  } as any)
const AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdEditRoute =
  AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () =>
      AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/rsc-test': typeof RscTestRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/f/$formId': typeof FFormIdRoute
  '/forms/$formId': typeof FormsFormIdRoute
  '/login/email': typeof LoginEmailRoute
  '/login/': typeof LoginIndexRoute
  '/workspace/$workspaceId': typeof AuthenticatedWorkspaceWorkspaceIdRouteRouteWithChildren
  '/api/ai/form-generate': typeof ApiAiFormGenerateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/aggregate-analytics': typeof ApiCronAggregateAnalyticsRoute
  '/api/cron/purge-archived-forms': typeof ApiCronPurgeArchivedFormsRoute
  '/api/icons/$name': typeof ApiIconsNameRoute
  '/forms/$i8n/$formId': typeof FormsI8nFormIdRoute
  '/api/forms/$formId/meta': typeof ApiFormsFormIdMetaRoute
  '/workspace/$workspaceId/form-builder/$formId': typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRouteWithChildren
  '/workspace/$workspaceId/form-builder/$formId/edit': typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdEditRoute
  '/workspace/$workspaceId/form-builder/$formId/insights': typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdInsightsRoute
  '/workspace/$workspaceId/form-builder/$formId/settings': typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdSettingsRoute
  '/workspace/$workspaceId/form-builder/$formId/submissions': typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdSubmissionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/rsc-test': typeof RscTestRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/f/$formId': typeof FFormIdRoute
  '/forms/$formId': typeof FormsFormIdRoute
  '/login/email': typeof LoginEmailRoute
  '/login': typeof LoginIndexRoute
  '/workspace/$workspaceId': typeof AuthenticatedWorkspaceWorkspaceIdRouteRouteWithChildren
  '/api/ai/form-generate': typeof ApiAiFormGenerateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/aggregate-analytics': typeof ApiCronAggregateAnalyticsRoute
  '/api/cron/purge-archived-forms': typeof ApiCronPurgeArchivedFormsRoute
  '/api/icons/$name': typeof ApiIconsNameRoute
  '/forms/$i8n/$formId': typeof FormsI8nFormIdRoute
  '/api/forms/$formId/meta': typeof ApiFormsFormIdMetaRoute
  '/workspace/$workspaceId/form-builder/$formId': typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRouteWithChildren
  '/workspace/$workspaceId/form-builder/$formId/edit': typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdEditRoute
  '/workspace/$workspaceId/form-builder/$formId/insights': typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdInsightsRoute
  '/workspace/$workspaceId/form-builder/$formId/settings': typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdSettingsRoute
  '/workspace/$workspaceId/form-builder/$formId/submissions': typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdSubmissionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/rsc-test': typeof RscTestRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/f/$formId': typeof FFormIdRoute
  '/forms/$formId': typeof FormsFormIdRoute
  '/login/email': typeof LoginEmailRoute
  '/login/': typeof LoginIndexRoute
  '/_authenticated/workspace/$workspaceId': typeof AuthenticatedWorkspaceWorkspaceIdRouteRouteWithChildren
  '/api/ai/form-generate': typeof ApiAiFormGenerateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/aggregate-analytics': typeof ApiCronAggregateAnalyticsRoute
  '/api/cron/purge-archived-forms': typeof ApiCronPurgeArchivedFormsRoute
  '/api/icons/$name': typeof ApiIconsNameRoute
  '/forms/$i8n/$formId': typeof FormsI8nFormIdRoute
  '/api/forms/$formId/meta': typeof ApiFormsFormIdMetaRoute
  '/_authenticated/workspace/$workspaceId/form-builder/$formId': typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRouteWithChildren
  '/_authenticated/workspace/$workspaceId/form-builder/$formId/edit': typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdEditRoute
  '/_authenticated/workspace/$workspaceId/form-builder/$formId/insights': typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdInsightsRoute
  '/_authenticated/workspace/$workspaceId/form-builder/$formId/settings': typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdSettingsRoute
  '/_authenticated/workspace/$workspaceId/form-builder/$formId/submissions': typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdSubmissionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/rsc-test'
    | '/dashboard'
    | '/f/$formId'
    | '/forms/$formId'
    | '/login/email'
    | '/login/'
    | '/workspace/$workspaceId'
    | '/api/ai/form-generate'
    | '/api/auth/$'
    | '/api/cron/aggregate-analytics'
    | '/api/cron/purge-archived-forms'
    | '/api/icons/$name'
    | '/forms/$i8n/$formId'
    | '/api/forms/$formId/meta'
    | '/workspace/$workspaceId/form-builder/$formId'
    | '/workspace/$workspaceId/form-builder/$formId/edit'
    | '/workspace/$workspaceId/form-builder/$formId/insights'
    | '/workspace/$workspaceId/form-builder/$formId/settings'
    | '/workspace/$workspaceId/form-builder/$formId/submissions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/rsc-test'
    | '/dashboard'
    | '/f/$formId'
    | '/forms/$formId'
    | '/login/email'
    | '/login'
    | '/workspace/$workspaceId'
    | '/api/ai/form-generate'
    | '/api/auth/$'
    | '/api/cron/aggregate-analytics'
    | '/api/cron/purge-archived-forms'
    | '/api/icons/$name'
    | '/forms/$i8n/$formId'
    | '/api/forms/$formId/meta'
    | '/workspace/$workspaceId/form-builder/$formId'
    | '/workspace/$workspaceId/form-builder/$formId/edit'
    | '/workspace/$workspaceId/form-builder/$formId/insights'
    | '/workspace/$workspaceId/form-builder/$formId/settings'
    | '/workspace/$workspaceId/form-builder/$formId/submissions'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/_authenticated'
    | '/rsc-test'
    | '/_authenticated/dashboard'
    | '/f/$formId'
    | '/forms/$formId'
    | '/login/email'
    | '/login/'
    | '/_authenticated/workspace/$workspaceId'
    | '/api/ai/form-generate'
    | '/api/auth/$'
    | '/api/cron/aggregate-analytics'
    | '/api/cron/purge-archived-forms'
    | '/api/icons/$name'
    | '/forms/$i8n/$formId'
    | '/api/forms/$formId/meta'
    | '/_authenticated/workspace/$workspaceId/form-builder/$formId'
    | '/_authenticated/workspace/$workspaceId/form-builder/$formId/edit'
    | '/_authenticated/workspace/$workspaceId/form-builder/$formId/insights'
    | '/_authenticated/workspace/$workspaceId/form-builder/$formId/settings'
    | '/_authenticated/workspace/$workspaceId/form-builder/$formId/submissions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  RscTestRoute: typeof RscTestRoute
  FFormIdRoute: typeof FFormIdRoute
  FormsFormIdRoute: typeof FormsFormIdRoute
  LoginEmailRoute: typeof LoginEmailRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ApiAiFormGenerateRoute: typeof ApiAiFormGenerateRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronAggregateAnalyticsRoute: typeof ApiCronAggregateAnalyticsRoute
  ApiCronPurgeArchivedFormsRoute: typeof ApiCronPurgeArchivedFormsRoute
  ApiIconsNameRoute: typeof ApiIconsNameRoute
  FormsI8nFormIdRoute: typeof FormsI8nFormIdRoute
  ApiFormsFormIdMetaRoute: typeof ApiFormsFormIdMetaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rsc-test': {
      id: '/rsc-test'
      path: '/rsc-test'
      fullPath: '/rsc-test'
      preLoaderRoute: typeof RscTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/email': {
      id: '/login/email'
      path: '/login/email'
      fullPath: '/login/email'
      preLoaderRoute: typeof LoginEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/$formId': {
      id: '/forms/$formId'
      path: '/forms/$formId'
      fullPath: '/forms/$formId'
      preLoaderRoute: typeof FormsFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$formId': {
      id: '/f/$formId'
      path: '/f/$formId'
      fullPath: '/f/$formId'
      preLoaderRoute: typeof FFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/forms/$i8n/$formId': {
      id: '/forms/$i8n/$formId'
      path: '/forms/$i8n/$formId'
      fullPath: '/forms/$i8n/$formId'
      preLoaderRoute: typeof FormsI8nFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/icons/$name': {
      id: '/api/icons/$name'
      path: '/api/icons/$name'
      fullPath: '/api/icons/$name'
      preLoaderRoute: typeof ApiIconsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/purge-archived-forms': {
      id: '/api/cron/purge-archived-forms'
      path: '/api/cron/purge-archived-forms'
      fullPath: '/api/cron/purge-archived-forms'
      preLoaderRoute: typeof ApiCronPurgeArchivedFormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/aggregate-analytics': {
      id: '/api/cron/aggregate-analytics'
      path: '/api/cron/aggregate-analytics'
      fullPath: '/api/cron/aggregate-analytics'
      preLoaderRoute: typeof ApiCronAggregateAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/form-generate': {
      id: '/api/ai/form-generate'
      path: '/api/ai/form-generate'
      fullPath: '/api/ai/form-generate'
      preLoaderRoute: typeof ApiAiFormGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspace/$workspaceId': {
      id: '/_authenticated/workspace/$workspaceId'
      path: '/workspace/$workspaceId'
      fullPath: '/workspace/$workspaceId'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkspaceIdRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/forms/$formId/meta': {
      id: '/api/forms/$formId/meta'
      path: '/api/forms/$formId/meta'
      fullPath: '/api/forms/$formId/meta'
      preLoaderRoute: typeof ApiFormsFormIdMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspace/$workspaceId/form-builder/$formId': {
      id: '/_authenticated/workspace/$workspaceId/form-builder/$formId'
      path: '/form-builder/$formId'
      fullPath: '/workspace/$workspaceId/form-builder/$formId'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRouteImport
      parentRoute: typeof AuthenticatedWorkspaceWorkspaceIdRouteRoute
    }
    '/_authenticated/workspace/$workspaceId/form-builder/$formId/submissions': {
      id: '/_authenticated/workspace/$workspaceId/form-builder/$formId/submissions'
      path: '/submissions'
      fullPath: '/workspace/$workspaceId/form-builder/$formId/submissions'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdSubmissionsRouteImport
      parentRoute: typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRoute
    }
    '/_authenticated/workspace/$workspaceId/form-builder/$formId/settings': {
      id: '/_authenticated/workspace/$workspaceId/form-builder/$formId/settings'
      path: '/settings'
      fullPath: '/workspace/$workspaceId/form-builder/$formId/settings'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdSettingsRouteImport
      parentRoute: typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRoute
    }
    '/_authenticated/workspace/$workspaceId/form-builder/$formId/insights': {
      id: '/_authenticated/workspace/$workspaceId/form-builder/$formId/insights'
      path: '/insights'
      fullPath: '/workspace/$workspaceId/form-builder/$formId/insights'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdInsightsRouteImport
      parentRoute: typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRoute
    }
    '/_authenticated/workspace/$workspaceId/form-builder/$formId/edit': {
      id: '/_authenticated/workspace/$workspaceId/form-builder/$formId/edit'
      path: '/edit'
      fullPath: '/workspace/$workspaceId/form-builder/$formId/edit'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdEditRouteImport
      parentRoute: typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRoute
    }
  }
}

interface AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRouteChildren {
  AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdEditRoute: typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdEditRoute
  AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdInsightsRoute: typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdInsightsRoute
  AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdSettingsRoute: typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdSettingsRoute
  AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdSubmissionsRoute: typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdSubmissionsRoute
}

const AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRouteChildren: AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRouteChildren =
  {
    AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdEditRoute:
      AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdEditRoute,
    AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdInsightsRoute:
      AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdInsightsRoute,
    AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdSettingsRoute:
      AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdSettingsRoute,
    AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdSubmissionsRoute:
      AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdSubmissionsRoute,
  }

const AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRouteWithChildren =
  AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRoute._addFileChildren(
    AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRouteChildren,
  )

interface AuthenticatedWorkspaceWorkspaceIdRouteRouteChildren {
  AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRoute: typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRouteWithChildren
}

const AuthenticatedWorkspaceWorkspaceIdRouteRouteChildren: AuthenticatedWorkspaceWorkspaceIdRouteRouteChildren =
  {
    AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRoute:
      AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRouteWithChildren,
  }

const AuthenticatedWorkspaceWorkspaceIdRouteRouteWithChildren =
  AuthenticatedWorkspaceWorkspaceIdRouteRoute._addFileChildren(
    AuthenticatedWorkspaceWorkspaceIdRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedWorkspaceWorkspaceIdRouteRoute: typeof AuthenticatedWorkspaceWorkspaceIdRouteRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedWorkspaceWorkspaceIdRouteRoute:
    AuthenticatedWorkspaceWorkspaceIdRouteRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  RscTestRoute: RscTestRoute,
  FFormIdRoute: FFormIdRoute,
  FormsFormIdRoute: FormsFormIdRoute,
  LoginEmailRoute: LoginEmailRoute,
  LoginIndexRoute: LoginIndexRoute,
  ApiAiFormGenerateRoute: ApiAiFormGenerateRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronAggregateAnalyticsRoute: ApiCronAggregateAnalyticsRoute,
  ApiCronPurgeArchivedFormsRoute: ApiCronPurgeArchivedFormsRoute,
  ApiIconsNameRoute: ApiIconsNameRoute,
  FormsI8nFormIdRoute: FormsI8nFormIdRoute,
  ApiFormsFormIdMetaRoute: ApiFormsFormIdMetaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
