/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as CreateRouteImport } from './routes/create'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiElectricRouteImport } from './routes/api/electric'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsMyAccountRouteImport } from './routes/_authenticated/settings/my-account'
import { Route as AuthenticatedSettingsBillingRouteImport } from './routes/_authenticated/settings/billing'
import { Route as AuthenticatedSettingsApiKeysRouteImport } from './routes/_authenticated/settings/api-keys'
import { Route as AuthenticatedWorkspaceWorkspaceIdRouteRouteImport } from './routes/_authenticated/workspace/$workspaceId/route'
import { Route as AuthenticatedWorkspaceWorkspaceIdIndexRouteImport } from './routes/_authenticated/workspace/$workspaceId/index'
import { Route as AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRouteImport } from './routes/_authenticated/workspace/$workspaceId/form-builder/$formId/route'
import { Route as AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdIndexRouteImport } from './routes/_authenticated/workspace/$workspaceId/form-builder/$formId/index'
import { Route as AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdSubmissionsRouteImport } from './routes/_authenticated/workspace/$workspaceId/form-builder/$formId/submissions'
import { Route as AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdShareRouteImport } from './routes/_authenticated/workspace/$workspaceId/form-builder/$formId/share'
import { Route as AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdSettingsRouteImport } from './routes/_authenticated/workspace/$workspaceId/form-builder/$formId/settings'
import { Route as AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdIntegrationsRouteImport } from './routes/_authenticated/workspace/$workspaceId/form-builder/$formId/integrations'
import { Route as AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdInsightsRouteImport } from './routes/_authenticated/workspace/$workspaceId/form-builder/$formId/insights'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiElectricRoute = ApiElectricRouteImport.update({
  id: '/api/electric',
  path: '/api/electric',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsMyAccountRoute =
  AuthenticatedSettingsMyAccountRouteImport.update({
    id: '/my-account',
    path: '/my-account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsBillingRoute =
  AuthenticatedSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsApiKeysRoute =
  AuthenticatedSettingsApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedWorkspaceWorkspaceIdRouteRoute =
  AuthenticatedWorkspaceWorkspaceIdRouteRouteImport.update({
    id: '/workspace/$workspaceId',
    path: '/workspace/$workspaceId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkspaceWorkspaceIdIndexRoute =
  AuthenticatedWorkspaceWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspaceWorkspaceIdRouteRoute,
  } as any)
const AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRoute =
  AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRouteImport.update({
    id: '/form-builder/$formId',
    path: '/form-builder/$formId',
    getParentRoute: () => AuthenticatedWorkspaceWorkspaceIdRouteRoute,
  } as any)
const AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdIndexRoute =
  AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRoute,
  } as any)
const AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdSubmissionsRoute =
  AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdSubmissionsRouteImport.update(
    {
      id: '/submissions',
      path: '/submissions',
      getParentRoute: () =>
        AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRoute,
    } as any,
  )
const AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdShareRoute =
  AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdShareRouteImport.update({
    id: '/share',
    path: '/share',
    getParentRoute: () =>
      AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRoute,
  } as any)
const AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdSettingsRoute =
  AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () =>
      AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRoute,
  } as any)
const AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdIntegrationsRoute =
  AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdIntegrationsRouteImport.update(
    {
      id: '/integrations',
      path: '/integrations',
      getParentRoute: () =>
        AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRoute,
    } as any,
  )
const AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdInsightsRoute =
  AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdInsightsRouteImport.update({
    id: '/insights',
    path: '/insights',
    getParentRoute: () =>
      AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/verify-email': typeof VerifyEmailRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/electric': typeof ApiElectricRoute
  '/workspace/$workspaceId': typeof AuthenticatedWorkspaceWorkspaceIdRouteRouteWithChildren
  '/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/settings/my-account': typeof AuthenticatedSettingsMyAccountRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/workspace/$workspaceId/': typeof AuthenticatedWorkspaceWorkspaceIdIndexRoute
  '/workspace/$workspaceId/form-builder/$formId': typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRouteWithChildren
  '/workspace/$workspaceId/form-builder/$formId/insights': typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdInsightsRoute
  '/workspace/$workspaceId/form-builder/$formId/integrations': typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdIntegrationsRoute
  '/workspace/$workspaceId/form-builder/$formId/settings': typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdSettingsRoute
  '/workspace/$workspaceId/form-builder/$formId/share': typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdShareRoute
  '/workspace/$workspaceId/form-builder/$formId/submissions': typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdSubmissionsRoute
  '/workspace/$workspaceId/form-builder/$formId/': typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/electric': typeof ApiElectricRoute
  '/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/settings/my-account': typeof AuthenticatedSettingsMyAccountRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/workspace/$workspaceId': typeof AuthenticatedWorkspaceWorkspaceIdIndexRoute
  '/workspace/$workspaceId/form-builder/$formId/insights': typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdInsightsRoute
  '/workspace/$workspaceId/form-builder/$formId/integrations': typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdIntegrationsRoute
  '/workspace/$workspaceId/form-builder/$formId/settings': typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdSettingsRoute
  '/workspace/$workspaceId/form-builder/$formId/share': typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdShareRoute
  '/workspace/$workspaceId/form-builder/$formId/submissions': typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdSubmissionsRoute
  '/workspace/$workspaceId/form-builder/$formId': typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/create': typeof CreateRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/api/electric': typeof ApiElectricRoute
  '/_authenticated/workspace/$workspaceId': typeof AuthenticatedWorkspaceWorkspaceIdRouteRouteWithChildren
  '/_authenticated/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/_authenticated/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/_authenticated/settings/my-account': typeof AuthenticatedSettingsMyAccountRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/workspace/$workspaceId/': typeof AuthenticatedWorkspaceWorkspaceIdIndexRoute
  '/_authenticated/workspace/$workspaceId/form-builder/$formId': typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRouteWithChildren
  '/_authenticated/workspace/$workspaceId/form-builder/$formId/insights': typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdInsightsRoute
  '/_authenticated/workspace/$workspaceId/form-builder/$formId/integrations': typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdIntegrationsRoute
  '/_authenticated/workspace/$workspaceId/form-builder/$formId/settings': typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdSettingsRoute
  '/_authenticated/workspace/$workspaceId/form-builder/$formId/share': typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdShareRoute
  '/_authenticated/workspace/$workspaceId/form-builder/$formId/submissions': typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdSubmissionsRoute
  '/_authenticated/workspace/$workspaceId/form-builder/$formId/': typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/verify-email'
    | '/settings'
    | '/dashboard'
    | '/api/electric'
    | '/workspace/$workspaceId'
    | '/settings/api-keys'
    | '/settings/billing'
    | '/settings/my-account'
    | '/settings/notifications'
    | '/api/auth/$'
    | '/settings/'
    | '/workspace/$workspaceId/'
    | '/workspace/$workspaceId/form-builder/$formId'
    | '/workspace/$workspaceId/form-builder/$formId/insights'
    | '/workspace/$workspaceId/form-builder/$formId/integrations'
    | '/workspace/$workspaceId/form-builder/$formId/settings'
    | '/workspace/$workspaceId/form-builder/$formId/share'
    | '/workspace/$workspaceId/form-builder/$formId/submissions'
    | '/workspace/$workspaceId/form-builder/$formId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/verify-email'
    | '/dashboard'
    | '/api/electric'
    | '/settings/api-keys'
    | '/settings/billing'
    | '/settings/my-account'
    | '/settings/notifications'
    | '/api/auth/$'
    | '/settings'
    | '/workspace/$workspaceId'
    | '/workspace/$workspaceId/form-builder/$formId/insights'
    | '/workspace/$workspaceId/form-builder/$formId/integrations'
    | '/workspace/$workspaceId/form-builder/$formId/settings'
    | '/workspace/$workspaceId/form-builder/$formId/share'
    | '/workspace/$workspaceId/form-builder/$formId/submissions'
    | '/workspace/$workspaceId/form-builder/$formId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/create'
    | '/verify-email'
    | '/_authenticated/settings'
    | '/_authenticated/dashboard'
    | '/api/electric'
    | '/_authenticated/workspace/$workspaceId'
    | '/_authenticated/settings/api-keys'
    | '/_authenticated/settings/billing'
    | '/_authenticated/settings/my-account'
    | '/_authenticated/settings/notifications'
    | '/api/auth/$'
    | '/_authenticated/settings/'
    | '/_authenticated/workspace/$workspaceId/'
    | '/_authenticated/workspace/$workspaceId/form-builder/$formId'
    | '/_authenticated/workspace/$workspaceId/form-builder/$formId/insights'
    | '/_authenticated/workspace/$workspaceId/form-builder/$formId/integrations'
    | '/_authenticated/workspace/$workspaceId/form-builder/$formId/settings'
    | '/_authenticated/workspace/$workspaceId/form-builder/$formId/share'
    | '/_authenticated/workspace/$workspaceId/form-builder/$formId/submissions'
    | '/_authenticated/workspace/$workspaceId/form-builder/$formId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CreateRoute: typeof CreateRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ApiElectricRoute: typeof ApiElectricRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/electric': {
      id: '/api/electric'
      path: '/api/electric'
      fullPath: '/api/electric'
      preLoaderRoute: typeof ApiElectricRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/my-account': {
      id: '/_authenticated/settings/my-account'
      path: '/my-account'
      fullPath: '/settings/my-account'
      preLoaderRoute: typeof AuthenticatedSettingsMyAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/billing': {
      id: '/_authenticated/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AuthenticatedSettingsBillingRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/api-keys': {
      id: '/_authenticated/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AuthenticatedSettingsApiKeysRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/workspace/$workspaceId': {
      id: '/_authenticated/workspace/$workspaceId'
      path: '/workspace/$workspaceId'
      fullPath: '/workspace/$workspaceId'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkspaceIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspace/$workspaceId/': {
      id: '/_authenticated/workspace/$workspaceId/'
      path: '/'
      fullPath: '/workspace/$workspaceId/'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkspaceIdIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspaceWorkspaceIdRouteRoute
    }
    '/_authenticated/workspace/$workspaceId/form-builder/$formId': {
      id: '/_authenticated/workspace/$workspaceId/form-builder/$formId'
      path: '/form-builder/$formId'
      fullPath: '/workspace/$workspaceId/form-builder/$formId'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRouteImport
      parentRoute: typeof AuthenticatedWorkspaceWorkspaceIdRouteRoute
    }
    '/_authenticated/workspace/$workspaceId/form-builder/$formId/': {
      id: '/_authenticated/workspace/$workspaceId/form-builder/$formId/'
      path: '/'
      fullPath: '/workspace/$workspaceId/form-builder/$formId/'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRoute
    }
    '/_authenticated/workspace/$workspaceId/form-builder/$formId/submissions': {
      id: '/_authenticated/workspace/$workspaceId/form-builder/$formId/submissions'
      path: '/submissions'
      fullPath: '/workspace/$workspaceId/form-builder/$formId/submissions'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdSubmissionsRouteImport
      parentRoute: typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRoute
    }
    '/_authenticated/workspace/$workspaceId/form-builder/$formId/share': {
      id: '/_authenticated/workspace/$workspaceId/form-builder/$formId/share'
      path: '/share'
      fullPath: '/workspace/$workspaceId/form-builder/$formId/share'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdShareRouteImport
      parentRoute: typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRoute
    }
    '/_authenticated/workspace/$workspaceId/form-builder/$formId/settings': {
      id: '/_authenticated/workspace/$workspaceId/form-builder/$formId/settings'
      path: '/settings'
      fullPath: '/workspace/$workspaceId/form-builder/$formId/settings'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdSettingsRouteImport
      parentRoute: typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRoute
    }
    '/_authenticated/workspace/$workspaceId/form-builder/$formId/integrations': {
      id: '/_authenticated/workspace/$workspaceId/form-builder/$formId/integrations'
      path: '/integrations'
      fullPath: '/workspace/$workspaceId/form-builder/$formId/integrations'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdIntegrationsRouteImport
      parentRoute: typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRoute
    }
    '/_authenticated/workspace/$workspaceId/form-builder/$formId/insights': {
      id: '/_authenticated/workspace/$workspaceId/form-builder/$formId/insights'
      path: '/insights'
      fullPath: '/workspace/$workspaceId/form-builder/$formId/insights'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdInsightsRouteImport
      parentRoute: typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsApiKeysRoute: typeof AuthenticatedSettingsApiKeysRoute
  AuthenticatedSettingsBillingRoute: typeof AuthenticatedSettingsBillingRoute
  AuthenticatedSettingsMyAccountRoute: typeof AuthenticatedSettingsMyAccountRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsApiKeysRoute: AuthenticatedSettingsApiKeysRoute,
    AuthenticatedSettingsBillingRoute: AuthenticatedSettingsBillingRoute,
    AuthenticatedSettingsMyAccountRoute: AuthenticatedSettingsMyAccountRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRouteChildren {
  AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdInsightsRoute: typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdInsightsRoute
  AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdIntegrationsRoute: typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdIntegrationsRoute
  AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdSettingsRoute: typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdSettingsRoute
  AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdShareRoute: typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdShareRoute
  AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdSubmissionsRoute: typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdSubmissionsRoute
  AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdIndexRoute: typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdIndexRoute
}

const AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRouteChildren: AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRouteChildren =
  {
    AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdInsightsRoute:
      AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdInsightsRoute,
    AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdIntegrationsRoute:
      AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdIntegrationsRoute,
    AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdSettingsRoute:
      AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdSettingsRoute,
    AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdShareRoute:
      AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdShareRoute,
    AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdSubmissionsRoute:
      AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdSubmissionsRoute,
    AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdIndexRoute:
      AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdIndexRoute,
  }

const AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRouteWithChildren =
  AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRoute._addFileChildren(
    AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRouteChildren,
  )

interface AuthenticatedWorkspaceWorkspaceIdRouteRouteChildren {
  AuthenticatedWorkspaceWorkspaceIdIndexRoute: typeof AuthenticatedWorkspaceWorkspaceIdIndexRoute
  AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRoute: typeof AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRouteWithChildren
}

const AuthenticatedWorkspaceWorkspaceIdRouteRouteChildren: AuthenticatedWorkspaceWorkspaceIdRouteRouteChildren =
  {
    AuthenticatedWorkspaceWorkspaceIdIndexRoute:
      AuthenticatedWorkspaceWorkspaceIdIndexRoute,
    AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRoute:
      AuthenticatedWorkspaceWorkspaceIdFormBuilderFormIdRouteRouteWithChildren,
  }

const AuthenticatedWorkspaceWorkspaceIdRouteRouteWithChildren =
  AuthenticatedWorkspaceWorkspaceIdRouteRoute._addFileChildren(
    AuthenticatedWorkspaceWorkspaceIdRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedWorkspaceWorkspaceIdRouteRoute: typeof AuthenticatedWorkspaceWorkspaceIdRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedWorkspaceWorkspaceIdRouteRoute:
    AuthenticatedWorkspaceWorkspaceIdRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CreateRoute: CreateRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ApiElectricRoute: ApiElectricRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
